name: Terraform validate
description: Terraform validate execution

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      run: terraform init
    
    - name: Terraform validate
      shell: bash
      run: terraform validate -no-color
